config/routes.rb
Rails.application.routes.draw do



  root 'welcome#index'

  get 'welcome/about' => 'welcome#about'

  get 'welcome/news' => 'welcome#news'

	get 'cv/education' => 'cv#education'	

	get 'cv/exhibition' => 'cv#exhibition'  

	get 'cv/activities' => 'cv#activities'

	get 'cv/membership' => 'cv#membership'

	get 'cv/grants'		=> 'cv/grants'

	get'portfolio/fabricprinting' => 'portfolio/fabricprinting'
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cv_controller.rb
class CvController < ApplicationController

	def education
	end

	def exhibition
	end

	def activities
	end

	def membership
	end

	def grants
	end

end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController

	def fabricprinting
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
	end

	def about
	end

	def news
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cv/activities.html.erb
<h2>Art related activities or assignments</h2>

<ul class="list-group">
<li class="list-group-item">2003 - <p>Kennari við Fossvogsskóla, Reykjavík</p></li>
<li class="list-group-item">1999		<p>Dómnefndarstarf í forvali vegna samkeppni um listskreytingu í nýbyggingu Barnaspítala Hringsins</p></li>
<li class="list-group-item">1998 - 2004<p>Ein af stofnendum Meistara Jakobs gallerís, Reykjavík</p></li>
<li class="list-group-item">1997 - 1999<p>Varamaður í stjórn Listskreytingasjóðs</p></li>
<li class="list-group-item">1996 - 1998<p>Fulltrúi Textílfélagsins í fulltrúaráði SÍM</p></li>
<li class="list-group-item">1995 - 1996<p>Kennari við Kennarháskóla Íslands</p></li>
<li class="list-group-item">1994 - 1998<p>Í stjórn Textílfélagsins</p></li>
<li class="list-group-item">1989 - 1993<p>Í sýningarnefnd Textílfélagsins</p></li>
<li class="list-group-item">1978 - 1986<p>Ein af stofnendum Gallerís Langbrókar, Reykjavík</p></li>
<li class="list-group-item">1977 - 1979<p>Formaður Textílfélagsins</p></li>
<li class="list-group-item">1976 - 1978<p>Ein af stofnendum Gallerís Sólon Íslandus, Aðalstræti 8, Reykjavík</p></li>
<li class="list-group-item">1975 - 1987<p>Kennari og deildarstjóri við Myndlista-og handíðaskóla Íslands</p></li>
</ul>

app/views/cv/education.html.erb
<h2>Myndlistarnám:</h2>

<ul class="list-group">
<li class="list-group-item">1968 - 72  <p>Myndlista-og handíðaskóli Íslands.</p></li>
<li class="list-group-item">1972 - 74  <p>Konstfackskólinn HKS í Stokkhólmi.</p></li>
<li class="list-group-item">1975       <P>Norrænt þrykknámskeið fyrir starfandi myndlistarmenn hjá Richard Künzl Stokkhólmi.</P></li>
</ul>

<h2>Workshops:</h2>
<ul class="list-group">
<li class="list-group-item">1989<p>Sveaborg Ateljéhuset Palmstierna HelsinkiFinnland</p></li>
<li class="list-group-item">2000<p>Kjarvalsstofa c/o Cité Internationale des ArtsParísFrakkland</p></li>
<li class="list-group-item">2010<p>Villa Bergshyddan - Lista- og fræðimannaíbúð</p></li>
</ul>

app/views/cv/exhibition.html.erb
<h2>Private Exhibition´s</h2>
<ul class="list-group">
<li class="list-group-item">2004	<p>Skálholtsskóli</p></li>
<li class="list-group-item">2003	<p>Hallgrímskirkja</p></li>
<li class="list-group-item">1998	<p>Bústaðakirkja</p></li>
<li class="list-group-item">1994	<p>SPRON</p></li>
<li class="list-group-item">1992	<p>Norræna húsið</p></li>
</ul>

<h2>Group exhibition's</h2>

<ul class="list-group">

<li class="list-group-item">2014	&nbsp;	<p>Afmælissýning Textílfélagsins í SÍM salnum</p></li>
<li class="list-group-item">2012	&nbsp;	<p>Textílfélagið á Korpúlfsstöðum</p></li>
<li class="list-group-item">2011	&nbsp;	<p>TEXTÍLFÉLAGIÐ Á LISTASUMRI Á AKUREYRI, í Ketilhúsi, Mjólkurbúð og Hofi.</p></li>
<li class="list-group-item">2010	&nbsp;	<p>“8th International Baltic Minitextil Triennial”, Gdynia, Póllandi.</p></li>
<li class="list-group-item">2010	&nbsp;	<p>“Með viljann að vopni” - Endurlit 1970 -1980, Kjarvalstöðum.</p></li>
<li class="list-group-item">2009	&nbsp;	<p>“ÞVERSKURÐUR“ - 35 ára afmæli Textílfélagsins, Listasafni Kópavogs.</p></li>
<li class="list-group-item">2007	&nbsp;	<p>“MINITEXTIL“ Textilmuseet, Borås.</p></li>
<li class="list-group-item">2007	&nbsp;	<p>“7th International Baltic Minitextil Triennial”, Gdynia, Póllandi.</p></li>
<li class="list-group-item">2006	&nbsp;	<p>“Mynd mín af Hallgrími, Hallgrímskirkja, Reykjavík.</p></li>
<li class="list-group-item">2006	&nbsp;	<p>“De Nordatlantiske Øer”, Ráðhúsi Kaupmannahafnar.	</p></li>
<li class="list-group-item">2002 – 08&nbsp;	 <p>„II-V International Artistic Linen Cloth Biennale”, Krosno, Póllandi.</p></li>
<li class="list-group-item">2002	&nbsp;	<p>Galleri Tablå, Bergen, Noregi.</p></li>
<li class="list-group-item">2002	&nbsp;	<p>Galleri Voss, Voss, Noregi.</p></li>
<li class="list-group-item">2001	&nbsp;	<p>„Asti – Reykjavík”, samsýning í Listasafni ASÍ, Reykjavík.</p></li>
<li class="list-group-item">2001	&nbsp;	<p>10th International Triennale of Tapestry, Lodz, Póllandi.</p> </li>
<li class="list-group-item">2001	&nbsp;	<p>„Armonte di contraste“, Asti, Ítalíu. </p></li>
<li class="list-group-item">2001	&nbsp;	<p>„Elementi d´Islanda“, Villa Badoglio, Asti, Ítalíu.</p></li>
<li class="list-group-item">2000	&nbsp;	<p>„Islandsk Samtidskunst“, Aurskog Höldan Kunstforening, Noregi.</p></li> 
<li class="list-group-item">2000	&nbsp;	<p>„Exposition collective des artistes de la Cité des Arts“, París. </p></li>
<li class="list-group-item">2000	&nbsp;	<p>„Hör“, Menningarmiðstöð Hafnarborg, Hafnarfirði.</p></li>
<li class="list-group-item">1999	&nbsp;	<p>25 ára afmælissýning Textílfélagsins í Listasafni Kópavogs.</p></li> 
<li class="list-group-item">1999	&nbsp;	<p>„Hör“, Langabúð, Djúpavogi. </p></li>
<li class="list-group-item">1999	&nbsp;	<p>„Near Distance“, Lochem, Hollandi.</p></li>
<li class="list-group-item">1997	&nbsp;	<p>Triennale International de Tournai, Belgíu.</p></li>
<li class="list-group-item">1995	&nbsp;	<p>20 ára afmælissýning Textílfélagsins í Hafnarborg, Hafnarfirði.</p></li> 
<li class="list-group-item">1995	&nbsp;	<p>8th International Triennale of Tapestry, Lodz, Póllandi. </p></li>
<li class="list-group-item">1996	&nbsp;	<p>11th International Miniature Textile Biennial Exhibition, Szombathelyi,
	Ungverjalandi.</p> </li>
<li class="list-group-item">1994	&nbsp;	<p>Samsýning á „Nordisk Forum“ Åbo Finnlandi.</p></li>
<li class="list-group-item">1992 	&nbsp;	<p>„Til lista lagt“, sýning á listskreytingum 10 listamanna sem styrktar hafa verið af Listskreytingasjóði, Ásmundarsal. </p> </li>
<li class="list-group-item">1992	&nbsp;	<p>„Kiek in de Kök“ samsýning 11 íslenskra listamanna í Tallinn,Eistlandi.  </p></li>
<li class="list-group-item">1992	&nbsp;	<p>„Fyrsti vetrardagur“ samsýning 5 listamanna, Listhús Laugardal. </p> </li>
<li class="list-group-item">1992 - 93 &nbsp;	<p>Form Island II - listiðnaður og hönnun, farandsýning um Norðurlönd.</p></li>
<li class="list-group-item">1990	&nbsp;	<p>„When Two Worlds Meet“, samsýning íslenskra og amerískra listamanna
	Warm gallery, Minneapolis.</p></li>
<li class="list-group-item">1989	&nbsp;	<p>Samsýning 4 listamanna í Slúnkaríki, Ísafirði.</p></li>
<li class="list-group-item">1988	&nbsp;	<p>Samsýning Textílfélagsins á Listahátíð, Norræna húsinu.</p></li>
<li class="list-group-item">1985	&nbsp;	<p>10 ára afmælissýning Textílfélagsins á Listahátíð,Kjarvalstöðum.</p></li>
<li class="list-group-item">1984	&nbsp;	<p>„Hexagon“ Norræn farandsýning 6 listamanna í:</p></li>  
	<li>&nbsp;	<p>Nollhaga Slott, Allingsås.</p></li>  
	<li>&nbsp;	<p>Galleri F.15, Moss.</p></li>  
	<li>&nbsp;	<p>Vestlandske Kunstindustrimuseum, Bergen.</p></li>  
	<li>&nbsp;	<p>Norræna húsinu, Reykjavík.</p></li>
<li class="list-group-item">1984	<p>Gallerí Langbrók á Listahátíð, Bogasal. </p></li>  
<li class="list-group-item">1984	<p>Gallerí Langbrók í Laxdalshúsi á Akureyri.</p></li>  
<li class="list-group-item">1982 - 83 <p>Nordisk Textiltriennal III, farandsýning um Norðurlönd.</p></li>    
<li class="list-group-item">1982 - 83 <p>„Scandinavian Modern Design, 1880-1980“ á Scandinavia Today, farandsýning í Bandaríkjunum.</p></li>  
<li class="list-group-item">1982	<p>Gallerí Langbrók hjá Textilgruppen í Stokkhólmi. </p></li>  
<li class="list-group-item">1982	<p>„Smælki“ Gallerí Langbrók á Listahátíð, Gallerí Langbrók.</p></li>  
<li class="list-group-item">1981	<p>Samsýning Textílfélagsins, Listasafni ASÍ.</p></li>  
<li class="list-group-item">1980	<p>„Smælki“ Gallerí Langbrók á Listahátíð, Gallerí Langbrók.</p></li>  
<li class="list-group-item">1979 - 80 <p>Nordisk Textiltriennal  II, farandsýning um Norðurlönd.</p></li>  
<li class="list-group-item">1979	<p>Sumarsýning Gallerís Langbrókar, Kjarvalsstöðum.</p></li>  
<li class="list-group-item">1978	<p>Samsýning Textílfélagsins, Norræna húsinu.</p></li>  
<li class="list-group-item">1977	<p>Gallerí Sólon Íslandus, samsýning aðstandenda Gallerís Sólon Íslandus.</p></li>  
<li class="list-group-item">1976 - 77 <p>Nordisk Textiltriennal  I, farandsýning um Norðurlönd.</p></li>  
<li class="list-group-item">1976	<p>Íslensk nytjalist, Norræna húsinu.</p></li>  
<li class="list-group-item">1975	<p>Listsýning íslenskra kvenna, Norræna húsinu.</p></li>    
</ul>

app/views/cv/grants.html.erb
<h2>Grants and awards</h2>

<ul class="list-group">
<li class="list-group-item">2008 <p>5th. International Artistic Linen Cloth Biennale Heiðursviðurkenning Viðurkenningar</p></li>
<li class="list-group-item">2008<p>The Akapi Foundation Heiðursverðlaun Viðurkenningar</p></li>
<li class="list-group-item">2004<p>Skálholt Staðarlistamaður Viðurkenningar</p></li>
<li class="list-group-item">2001<p>Launasjóður myndlistarmanna Starfsstyrkur Styrkir</p></li>
<li class="list-group-item">1995<p>Launasjóður myndlistarmanna Starfsstyrkur Styrkir</p></li>
<li class="list-group-item">1983<p>Launasjóður myndlistarmanna Starfsstyrkur Styrkir</p></li>
<li class="list-group-item">1981<p>Menningarsjóður Íslands og Finnlands / Kulturfonden Island-Finland Sýningar- og ferðastyrkur Styrkir</p></li>
<li class="list-group-item">1972<p>Myndlista- og handíðaskóli Íslands Viðurkenning í samkeppni á vegum stofnunarinnar Viðurkenningar</p></li>
</ul>

app/views/cv/membership.html.erb
<h2>Memberships</h2>
<ul class="list-group">
<li class="list-group-item"><p>Society of Textile Artists</p></li>
<li class="list-group-item"><p>The Association of Icelandic Visual Artists</p></li>
<li class="list-group-item"><p>Icelandic Teachers Union</p></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thorbjorgth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<%= render "welcome/jumbo" %>
	<%= render "welcome/navbar" %>
	<%= yield %>
</div>
</body>
</html>

app/views/portfolio/fabricprinting.html.erb
<h1 class='page-header'>Fabric Printing</h1>
<div class="PortfolioContainer">
<h4> 1972 - 1980</h4>
<div class="row">
                        <div class="col-md-offset-2 col-md-6">
                            <div class="row">
<%= link_to image_tag("/assets/portfolio/01pattern_closeup.jpg", height:'105px', class: "col-sm-3"), "/assets/portfolio/01pattern_closeup.jpg", data:{ title:'Pattern Fabric Print CloseUp', footer:'Fabric Printing 1972', toggle:'lightbox', gallery:'multiimages' }, class: "img-responsive"%>
	
<%=  link_to image_tag("/assets/portfolio/01pattern1972.jpg", height:'105px', class: "col-sm-3"), "/assets/portfolio/01pattern1972.jpg", data:{ title:'Pattern - Fabric Print', footer:'Fabric Printing 1972', toggle:'lightbox', gallery:'multiimages' }, class: "img-responsive" %>

<%= link_to image_tag("/assets/portfolio/02pattern_closeup72.jpg", height:'105px', class: "col-sm-3"), "/assets/portfolio/02pattern_closeup72.jpg", data:{ title:'Pattern - Fabric Print CloseUp', footer:'Fabric Printing 1972', toggle:'lightbox', gallery:'multiimages' }, class: "img-responsive" %>

<%= link_to image_tag("/assets/portfolio/02pattern1972.jpg", height:'105px', class: "col-sm-3"), "/assets/portfolio/02pattern1972.jpg", data:{ title:'Pattern - Fabric Print CloseUp', footer:'Fabric Printing 1972', toggle:'lightbox', gallery:'multiimages' }, class: "img-responsive" %>


</div>
<div class="row">

<%= link_to image_tag("/assets/portfolio/01pattern_closeup.jpg", height:'105px', class: "col-sm-3"), "/assets/portfolio/01pattern_closeup.jpg", data:{ title:'Pattern Fabric Print CloseUp', footer:'Fabric Printing 1972', toggle:'lightbox', gallery:'multiimages' }, class: "img-responsive"%>
<%= link_to image_tag("/assets/portfolio/01pattern_closeup.jpg", height:'105px', class: "col-sm-3"), "/assets/portfolio/01pattern_closeup.jpg", data:{ title:'Pattern Fabric Print CloseUp', footer:'Fabric Printing 1972', toggle:'lightbox', gallery:'multiimages' }, class: "img-responsive"%>
<%= link_to image_tag("/assets/portfolio/01pattern_closeup.jpg", height:'105px', class: "col-sm-3"), "/assets/portfolio/01pattern_closeup.jpg", data:{ title:'Pattern Fabric Print CloseUp', footer:'Fabric Printing 1972', toggle:'lightbox', gallery:'multiimages' }, class: "img-responsive"%>
<%= link_to image_tag("/assets/portfolio/01pattern_closeup.jpg", height:'105px', class: "col-sm-3"), "/assets/portfolio/01pattern_closeup.jpg", data:{ title:'Pattern Fabric Print CloseUp', footer:'Fabric Printing 1972', toggle:'lightbox', gallery:'multiimages' }, class: "img-responsive"%>

</div>
</div>

app/views/welcome/_jumbo.html.erb
<div class="jumbotron">
  <h1 align="center">Þorbjörg Þórðardóttir</h1>
  <h3 align="center">Textil Designer</h3>
  <!--<p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>-->
</div>

app/views/welcome/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li><%= link_to "Home", root_path, class: "navbutt" %></li>
            <li><%= link_to "About", welcome_about_path, class: "navbutt" %></li>
            <li><%= link_to "News", welcome_news_path, class: "navbutt" %></li>

        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Portfolio <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Fabric Printing", portfolio_fabricprinting_path, clas: "navbutt" %> </li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
                <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">CV <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Education & Workshops", cv_education_path, class: "navbutt" %></li>
            <li><%= link_to "Exhibitions", cv_exhibition_path, class: "navbutt" %></li>

            
            <li><%= link_to "Art related activities or assignments

", cv_activities_path, class: "navbutt" %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Memberships", cv_membership_path, class: "navbutt" %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Grants and Awards", cv_grants_path, class: "navbutt" %></li>
          </ul>
          <li><a href="#">Subscribe to newsletter</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/welcome/about.html.erb
<h1>This is the about page </h1>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc rhoncus leo vitae neque malesuada ultricies. Praesent pulvinar congue nulla eu fermentum. Nulla felis erat, eleifend ut metus et, volutpat feugiat erat. Fusce id dignissim nulla. Sed tortor nunc, suscipit a feugiat ut, facilisis rhoncus metus. Vivamus id molestie tortor. Quisque iaculis vel mauris id tincidunt. Nullam ligula arcu, suscipit eu finibus sit amet, ultrices quis libero. Duis volutpat nulla a tortor semper, id placerat nulla pulvinar. Sed vel congue nisl. Sed a ipsum nec libero mattis molestie. Nunc imperdiet vitae mauris quis consectetur. Fusce pulvinar elementum mauris eget porttitor. Donec ac odio id lectus lobortis molestie in quis magna. Proin varius massa eu justo sagittis, non mattis metus lacinia. Pellentesque orci magna, venenatis aliquet mauris quis, laoreet blandit nunc.</p>

</br>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc rhoncus leo vitae neque malesuada ultricies. Praesent pulvinar congue nulla eu fermentum. Nulla felis erat, eleifend ut metus et, volutpat feugiat erat. Fusce id dignissim nulla. Sed tortor nunc, suscipit a feugiat ut, facilisis rhoncus metus. Vivamus id molestie tortor. Quisque iaculis vel mauris id tincidunt. Nullam ligula arcu, suscipit eu finibus sit amet, ultrices quis libero. Duis volutpat nulla a tortor semper, id placerat nulla pulvinar. Sed vel congue nisl. Sed a ipsum nec libero mattis molestie. Nunc imperdiet vitae mauris quis consectetur. Fusce pulvinar elementum mauris eget porttitor. Donec ac odio id lectus lobortis molestie in quis magna. Proin varius massa eu justo sagittis, non mattis metus lacinia. Pellentesque orci magna, venenatis aliquet mauris quis, laoreet blandit nunc.</p>

app/views/welcome/index.html.erb
<h1> Hello</h1>

app/views/welcome/news.html.erb
<h1>this is the news page</h1>